const metricDefinitions=[
['Safety','Incidents / near misses','0'],['Safety risk assessment','Trigger level','Low'],['Food safety','Quality triggers','Low'],['CIL packaging','Completion','100%'],['CL packaging','Out of centerline','0'],['Defect handling','Found / fixed','≥1 / ≥1'],['Breakdowns','Breakdowns','0'],['Work process failures','Failures','0'],['Schedule attainment','Produced / scheduled','≥100%'],['Robert stops','Number of stops','<4 / shift'],['Ingredient overuse','Percent overuse','<0.5%'],['MTBF','Uptime between stops','>115 min'],['Refeed','Number of partials','≤1']];

const lineMetrics={S:[
[['0','0','0','—','—'],['green','green','green','empty','empty']],[['Low','Low','Low','—','—'],['green','green','green','empty','empty']],[['Low','Low','1 high','—','—'],['green','green','red','empty','empty']],[['100%','100%','96%','—','—'],['green','green','red','empty','empty']],[['0','0','1','—','—'],['green','green','amber','empty','empty']],[['0 / 0','1 / 1','2 / 2','—','—'],['red','green','green','empty','empty']],[['0','0','0','—','—'],['green','green','green','empty','empty']],[['0','0','0','—','—'],['green','green','green','empty','empty']],[['100%','104%','104%','—','—'],['green','green','green','empty','empty']],[['11','3','4','—','—'],['red','green','amber','empty','empty']],[['0.15%','0.16%','0.19%','—','—'],['green','green','green','empty','empty']],[['45','140','132','—','—'],['red','green','green','empty','empty']],[['0.25','0.50','2','—','—'],['green','green','red','empty','empty']]
],T:[
[['0','0','0','—','—'],['green','green','green','empty','empty']],[['Low','Low','Low','—','—'],['green','green','green','empty','empty']],[['Low','Low','Low','—','—'],['green','green','green','empty','empty']],[['100%','98%','100%','—','—'],['green','amber','green','empty','empty']],[['0','0','0','—','—'],['green','green','green','empty','empty']],[['1 / 1','1 / 1','1 / 1','—','—'],['green','green','green','empty','empty']],[['0','1','0','—','—'],['green','red','green','empty','empty']],[['0','0','0','—','—'],['green','green','green','empty','empty']],[['102%','97%','101%','—','—'],['green','red','green','empty','empty']],[['2','6','3','—','—'],['green','red','green','empty','empty']],[['0.22%','0.28%','0.20%','—','—'],['green','green','green','empty','empty']],[['126','88','121','—','—'],['green','red','green','empty','empty']],[['0.50','1','0.75','—','—'],['green','green','green','empty','empty']]
]};

const currentWeekActions=[
['Omega non-stop product fill','Escalated from Sep 13 DDS','S','Reliability','CB','Maintenance','Sep 14','3d','Overdue'],['Refeed pan variation','Measure amplitude at three load points','S','Quality','TR','Process Eng.','Sep 15','2d','Overdue'],['Verify elevator chain tension','Complete post-changeover inspection','S','Reliability','CB','Maintenance','Today','6h','Open'],['Run splice detection challenge','Confirm alarm and reject timing','T','Quality','AM','Quality','Today','4h','Open'],['Centerline deviation follow-up','Verify operator settings','T','Delivery','JS','Operations','Today','3h','Open'],['Update changeover checklist','Add elevator inspection point','S','Reliability','JS','Operations','Sep 16','1d','Verify'],['Review CIL completion gap','Confirm missed inspection reason','T','Safety','KL','Safety','Sep 17','2h','Open'],['Ingredient overuse control limits','Validate warning threshold','T','Cost','TR','Process Eng.','Sep 20','5h','Open']];
let nextWeekActions=null;

let activeLine='all',activeWeek='current';
function combinedMetrics(){return metricDefinitions.map((d,row)=>{const s=lineMetrics.S[row],t=lineMetrics.T[row],severity={empty:0,green:1,amber:2,red:3};return [...d,s[0].map((v,i)=>v==='—'&&t[0][i]==='—'?'—':v===t[0][i]?v:`${v} / ${t[0][i]}`),s[1].map((v,i)=>severity[v]>=severity[t[1][i]]?v:t[1][i])];})}
function currentMetrics(){if(activeWeek==='next')return metricDefinitions.map(d=>[...d,['—','—','—','—','—'],['empty','empty','empty','empty','empty']]);if(activeLine==='all')return combinedMetrics();return metricDefinitions.map((d,i)=>[...d,lineMetrics[activeLine][i][0],lineMetrics[activeLine][i][1]])}
function renderMetrics(){document.getElementById('metricBody').innerHTML=currentMetrics().map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td class="target">${r[2]}</td>${r[3].map((v,i)=>`<td${i===2&&activeWeek==='current'?' class="today-col"':''}><button class="metric-cell ${r[4][i]}" data-problem="${r[0]} — ${r[1]}">${v}</button></td>`).join('')}</tr>`).join('');document.querySelectorAll('.metric-cell.red,.metric-cell.amber').forEach(el=>el.addEventListener('click',()=>openModal(el.dataset.problem)))}
function actionSet(){return activeWeek==='next'?(nextWeekActions||[]):currentWeekActions}
function renderActions(filter=''){const rows=actionSet().filter(a=>(activeLine==='all'||a[2]===activeLine)&&a.join(' ').toLowerCase().includes(filter.toLowerCase()));document.getElementById('actionTableBody').innerHTML=rows.map(a=>`<tr><td>${a[0]}<small>${a[1]}</small></td><td><span class="line-chip">${a[2]}</span></td><td>${a[3]}</td><td><div class="owner-chip"><span class="mini-avatar">${a[4]}</span><span>${a[5]}</span></div></td><td>${a[6]}</td><td>${a[7]}</td><td><span class="status-badge status-${a[8].toLowerCase()}">${a[8]}</span></td></tr>`).join('')}
function updateContext(){const name=activeLine==='all'?'S + T':activeLine,isCurrent=activeWeek==='current';document.getElementById('boardLineChip').textContent=name;document.getElementById('weekLabel').textContent=isCurrent?'Week of September 14–18, 2026':'Week of September 21–25, 2026';document.getElementById('metricHead').innerHTML=`<tr><th>Category</th><th>Metric</th><th>Target</th>${(isCurrent?['Mon 14','Tue 15','Wed 16','Thu 17','Fri 18']:['Mon 21','Tue 22','Wed 23','Thu 24','Fri 25']).map((d,i)=>`<th${isCurrent&&i===2?' class="today-col"':''}>${d}</th>`).join('')}</tr>`;renderMetrics();renderActions()}
function showView(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));window.scrollTo(0,0)}
document.querySelectorAll('.nav-item').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.view)));
document.querySelectorAll('.nav-goto').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.goto)));

const modal=document.getElementById('modalBackdrop');
function openModal(problem=''){modal.hidden=false;document.getElementById('problemInput').value=problem;document.getElementById('actionLine').value=activeLine==='all'?'S':activeLine;document.getElementById('problemInput').focus()}
function closeModal(){modal.hidden=true}
document.getElementById('addActionBtn').addEventListener('click',()=>openModal());document.querySelectorAll('.add-action').forEach(b=>b.addEventListener('click',()=>openModal()));document.querySelectorAll('.stop-item').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.action)));document.getElementById('modalClose').addEventListener('click',closeModal);document.getElementById('cancelBtn').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
document.getElementById('actionForm').addEventListener('submit',e=>{e.preventDefault();const p=document.getElementById('problemInput').value||'New DDS action',line=document.getElementById('actionLine').value,target=activeWeek==='next'?(nextWeekActions||(nextWeekActions=[])):currentWeekActions;target.unshift([p,'Created from DDS dashboard',line,'Reliability','CB','Maintenance',activeWeek==='next'?'Sep 25':'Sep 17','Now','Open']);renderActions();closeModal();showToast(`${line} Line action created`)});

const weekModal=document.getElementById('weekBackdrop');function closeWeekModal(){weekModal.hidden=true}
document.getElementById('newWeekBtn').addEventListener('click',()=>{weekModal.hidden=false});document.getElementById('weekClose').addEventListener('click',closeWeekModal);document.getElementById('weekCancel').addEventListener('click',closeWeekModal);weekModal.addEventListener('click',e=>{if(e.target===weekModal)closeWeekModal()});
document.getElementById('confirmWeek').addEventListener('click',()=>{activeWeek='next';document.getElementById('weekSelect').value='next';nextWeekActions=currentWeekActions.filter(a=>a[8]!=='Verify').map(a=>{const copy=[...a];copy[1]=`Carried from Sep 14–18 · ${copy[1]}`;return copy});closeWeekModal();updateContext();showToast('New week started · 7 actions carried forward')});
function showToast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelectorAll('.check').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('done');b.textContent=b.classList.contains('done')?'✓':''}));document.getElementById('actionSearch').addEventListener('input',e=>renderActions(e.target.value));document.querySelectorAll('.filter').forEach(f=>f.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');const q=f.textContent.includes('Overdue')?'Overdue':f.textContent.includes('Due today')?'Today':'';renderActions(q)}));
document.getElementById('presentBtn').addEventListener('click',()=>{document.body.classList.toggle('presentation');document.getElementById('presentBtn').textContent=document.body.classList.contains('presentation')?'◉ Exit presentation':'◉ Present DDS'});
document.getElementById('lineSelect').addEventListener('change',e=>{activeLine=e.target.value;updateContext();showToast(`Showing ${activeLine==='all'?'S + T Lines':activeLine+' Line'}`)});document.getElementById('weekSelect').addEventListener('change',e=>{activeWeek=e.target.value;updateContext()});updateContext();
